def get_ans(qid: int) -> str:
    anses = '.ACEFADCEEECFDDADDDDCFFCFEDFFBAEBABFCBFFFCDCDEDCABAACABEEDFBDBFDDBDCAFEDCAFFECFFADBADEEDBBEAECFDDEBDFAFEBADCFEE'
    return anses[qid]

# .ACEFADCEEECFDDADDDDCFFCFEDFFBAEBABFCBFFFCDCDEDCABAACABEEDFBDBFDDBDCAFEDCAFFECFFADBADEEDBBEAECFDDFBDFBFBCD56789'